//FOR APPOINTMENTS MANAGEMENT
var APPOINTMENTS_SS_ID = "1DkJbZuo--p8KRSt7dsU2mEA67jNzaC2fb1sy5stEEPY";
var APPOINTMENTS_SHEET_NAME = "Agendamentos";

//FOR FORM FEEGOW REPORT
var REPORTS_SS_ID = "1REZTL5iiqnOknbuo5Scs1JwugYism2OvJ3kSlQoO0Qw";
var REPORT_PATIENTS_SHEET_NAME = "Pacientes";
var REPORT_RET_SCHEDULE_SHEET_NAME = "Programação de retorno";
var REPORT_BILLS_TO_RECEIVE_SHEET_NAME = "Contas a receber";

//FOR FORM UNIVITTA MONITORING
var UNIVITTA_MONITORING_SS_ID = "1HrZXstC-yd6WWS5EObWlMxikRwYZq1u1eZbNo8b7CM4";
var UNIVITTA_MONITORING_REGISTER_SHEET_NAME = "Cadastros";

//FOR GOOGLE DRIVE AUTOMARTION
var README_FILE_ID = "19bBjCCQJBpcoGxkHLmckXDvQIBi3ZaGx1V4Iil_raM4";
var ALL_PATIENTS_FOLDER_ID = "16YOV6DXHZ1CBBb-aRM1V6Pdz8zXreEJs";
var TODAY_PATIENTS_FOLDER_ID = "1-jFUF4HvOC6opJThuCtL1PksTWvIy3gO";
var TEMPLATE_DOCUMENT_WITH_QRCODE_ID = "16VyDpE7MsRb6FIWQjJ_fScHgDK0YdyJpGrvkXRtu-D8";

//CONTROLE DE CARTÕES DO TRELLO
// https://docs.google.com/spreadsheets/d/1HDPVqAO76TODXCM07VRX0I6vOg3Z0xbiOZbnH3tdAE0
var TASKS_SS_ID = '1HDPVqAO76TODXCM07VRX0I6vOg3Z0xbiOZbnH3tdAE0';
var CARDS_TAB_NAME = 'Cartões';
var ROUTINES_TAB_NAME = 'Rotinas';
var HOLIDAYS_TAB_NAME = 'Feriados';


